import type { NextPage } from "next";
import Head from "next/head";
import Shipping from "../shipping/";
import Payment from "./payment";
import Order from "./order";

const Checkout: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Checkout Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Shipping />
                <Order />
                <Payment />
            </main>
        </div>
    );
};

export default Checkout;
