import type { NextPage } from "next";
import Head from "next/head";
import ProductsCards from "../components/home/ProductCards";
import Hero from "../components/home/Hero";

{
    /* import { useQuery, gql } from "@apollo/client"; */
}
{
    /* import { GET_LOGGED_USER_QUERY } from "../backend/graphql/queries/logUser"; */
}

const Home: NextPage = () => {
    {
        /*     const { loading, error, data } = useQuery(GET_LOGGED_USER_QUERY); */
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Hero />

                <ProductsCards />
            </main>
        </div>
    );
};

export default Home;
